services:
    logger:
        class: service\logger

    definitionContructor:
        class: service\Chat
        arguments: [@logger]
        properties:
            name: constructor
        tags:
            - { name: chat }