testextension:
    foo: 1
    bar: 2

parameters:
    logger.class: Service\logger
    chat.class: Service\Chat
    root: ""

services:
    logger.file:
        class: %logger.class%
        lazy: true
        file: lib/ColorConsole.php
        public: false

    logger:
        alias: logger.file

    definitionConstructor:
        class: %chat.class%
        arguments: [@logger]
        properties:
            name: constructor
        tags:
            - { name: chat, alias: constructor }

    definitionSetter:
        class: %chat.class%
        calls:
            - [setLogger, [@logger]]
        properties:
            name: setter
        tags:
            - { name: chat, alias: setter }

    definitionProperty:
        class: %chat.class%
        properties:
            name: property
            logger: @logger
        tags:
            - { name: chat, alias: property }

    chat.configurator:
        class: Configurator\Chat
        arguments: [@logger]

    definitionConfigurator:
        class: %chat.class%
        properties:
            name: configurator
        configurator: ["@chat.configurator", configure]
        tags:
            - { name: chat, alias: configurator }

    definitionFactory:
        class: %chat.class%
        arguments: [@logger]
        properties:
            name: factory
        factory: "Factory\Chat::factory"
        tags:
            - { name: chat, alias: factory }

    definitionExpression:
        class: %chat.class%
        arguments: [@=container.get('logger')]
        tags:
            - { name: chat, alias: expression }

    defininitionSynthetic:
        synthetic: true
        tags:
            - { name: chat, alias: synthetic }

